import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Brain, Lightbulb, Sparkles, TrendingUp } from "lucide-react";

import { AppShell } from "@/components/layout/AppShell";
import {
  EmptyState,
  ErrorState,
  LoadingState,
  SectionCard,
  inr,
} from "@/components/recoverai/common";
import { Button } from "@/components/ui/button";
import { getInsights } from "@/services/api";

export const Route = createFileRoute("/insights")({
  head: () => ({
    meta: [
      { title: "AI Insights — RecoverAI" },
      {
        name: "description",
        content:
          "AI-generated executive summary, revenue risk analysis, behaviour patterns and recommended recovery actions.",
      },
      { property: "og:title", content: "AI Insights — RecoverAI" },
      {
        property: "og:description",
        content: "Executive summary and recommended actions generated from your recovery data.",
      },
    ],
  }),
  component: InsightsPage,
});

function InsightsPage() {
  const query = useQuery({ queryKey: ["insights"], queryFn: getInsights, retry: false });

  return (
    <AppShell
      title="AI Insights"
      subtitle="What the AI engine sees in your revenue data"
      actions={
        <Button size="sm" variant="outline" onClick={() => query.refetch()}>
          <Sparkles className="size-4" /> Regenerate
        </Button>
      }
    >
      {query.isLoading ? (
        <LoadingState label="Generating insights..." />
      ) : query.error || !query.data ? (
        <ErrorState error={query.error} onRetry={() => query.refetch()} />
      ) : (
        <div className="space-y-6">
          <div className="rounded-2xl bg-primary p-6 text-primary-foreground shadow-[var(--shadow-pop)]">
            <div className="flex items-start gap-3">
              <Brain className="mt-0.5 size-6 shrink-0" />
              <div>
                <p className="text-sm font-semibold uppercase tracking-wide opacity-90">
                  Executive summary
                </p>
                <p className="mt-1 text-base leading-relaxed">{query.data.executiveSummary}</p>
                <p className="mt-2 text-xs opacity-80">
                  {query.data.aiGenerated
                    ? "Generated by the RecoverAI language model."
                    : "Calculated from your live recovery data."}
                </p>
              </div>
            </div>
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            <SectionCard title="Revenue risk analysis" description="Key exposure figures">
              <div className="grid gap-3 sm:grid-cols-2">
                {query.data.revenueRisk.map((item) => (
                  <div key={item.label} className="rounded-lg border border-border p-3">
                    <p className="text-xs text-muted-foreground">{item.label}</p>
                    <p className="mt-1 text-lg font-semibold">{item.value}</p>
                  </div>
                ))}
              </div>
              <p className="mt-4 flex items-center gap-2 text-sm font-medium text-success">
                <TrendingUp className="size-4" />
                Estimated recoverable: {inr(query.data.potentialRecovery)}
              </p>
            </SectionCard>

            <SectionCard
              title="Top recovery opportunities"
              description="Customers worth acting on first"
            >
              {query.data.topOpportunities.length === 0 ? (
                <EmptyState title="No open opportunities." />
              ) : (
                <ul className="space-y-2">
                  {query.data.topOpportunities.map((item) => (
                    <li
                      key={item.name}
                      className="flex items-center justify-between gap-3 rounded-lg border border-border p-3"
                    >
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium">{item.name}</p>
                        <p className="truncate text-xs text-muted-foreground">{item.reason}</p>
                      </div>
                      <span className="shrink-0 text-sm font-semibold">{inr(item.amount)}</span>
                    </li>
                  ))}
                </ul>
              )}
            </SectionCard>
          </div>

          <div className="grid gap-4 lg:grid-cols-2">
            <SectionCard title="Customer behaviour patterns" description="Signals across your base">
              <ul className="space-y-2">
                {query.data.behaviourPatterns.map((pattern) => (
                  <li key={pattern} className="flex gap-2 text-sm text-muted-foreground">
                    <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-primary" />
                    {pattern}
                  </li>
                ))}
              </ul>
            </SectionCard>

            <SectionCard title="Payment failure patterns" description="Most common failure reasons">
              {query.data.failurePatterns.length === 0 ? (
                <EmptyState title="No failure patterns detected." />
              ) : (
                <ul className="space-y-2">
                  {query.data.failurePatterns.map((item) => (
                    <li
                      key={item.reason}
                      className="flex items-center justify-between gap-3 rounded-lg border border-border p-3 text-sm"
                    >
                      <span className="truncate">{item.reason}</span>
                      <span className="shrink-0 font-semibold">{item.count}</span>
                    </li>
                  ))}
                </ul>
              )}
            </SectionCard>
          </div>

          <SectionCard title="Recommended actions" description="What RecoverAI suggests next">
            <ul className="space-y-2">
              {query.data.recommendedActions.map((action) => (
                <li
                  key={action}
                  className="flex items-start gap-3 rounded-lg bg-primary-soft p-3 text-sm"
                >
                  <Lightbulb className="mt-0.5 size-4 shrink-0 text-primary" />
                  {action}
                </li>
              ))}
            </ul>
          </SectionCard>
        </div>
      )}
    </AppShell>
  );
}
